### ISSUE TITLE
Spell Roll does nothing

### ISSUE THREAD

**Issue by jensenator** [elizeuangelo/fvtt-beyond-the-wall#1]
The spell Roll does nothing. Must add "d20+@actor.abilities.int.mod" on the Macro field or something?

**Comment by ChiefEinherjar** [comment]
It seems, that we have the same problem. I posted about this on Reddit and got sent here - and it seems, that it is an issue indeed.

https://www.reddit.com/r/FoundryVTT/comments/122r3ik/beyond_the_wall_spellsarmor_dont_seem_to_work/

**Comment by elizeuangelo** [comment]
The spell rolls whats in the macro field. It doesnt make an "attack" or something like that, as the weapon roll does.

**Comment by ChiefEinherjar** [comment]
With that hint, I've at least figured out, that I have to add "d20" in the "Macro"-field. But is there a way to automatically add the intelligence (or wisdom or whatever) modifier to the roll? - Or at least manually? Because I didn't even find a possibility to add any kind of modifier in any way.
Or is there a way, to call a macro from that field? 
And maybe couldn't you make the spell do basically an "attack"? - The mechanics are basically the same...

I mean - don't get me wrong; I absolutely appreciate your work! Just giving some feedback on what could be improved :)

**Comment by elizeuangelo** [comment]
> But is there a way to automatically add the intelligence (or wisdom or whatever) modifier to the roll?

Use `@int` or `@wis`.

> And maybe couldn't you make the spell do basically an "attack"? - The mechanics are basically the same...

I dont play the system nor built it. I just updated it to v10 in a comission. Im not sure why `studio315b` built it this way, but maybe not all spells behave the same? Some spells might have saves or some other mechanic entirely?

**Comment by ChiefEinherjar** [comment]
Thanks for your reply!
Duhh... stupid me. I tried typing "@abilities.int but that added the score itself - @int or @wis was perfect! Now I can at least add all the spells and let them roll correctly.

Just to clarify how spells in this system work: You always have to make an int or a wis-check (it's specified in the rulebook for each spell). If you pass the check, the spell works as intended (and maybe the enemy is indeed required to roll a save - but that's not what I meant). If you fail the check... well... baaaad things happen ;)

Anyways - thanks for your help! I'm new to foundry and those hints have helped me, to get started.

Maybe, some time in the future, I'll do a fork and implement some things, I think would make the foundry-plugin/system better. But that is just another thing on a loooooooooooooooooong ass list of things I want to do...
